version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8888:8888"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - BANKING_API_BASE_URL=http://banking-api:3000
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network

  banking-api:
    image: trkha16/banking-api:latest
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
