version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: internet_banking
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3307:3306"
    expose:
        - 3307
    volumes:
      - ./sql-scripts/internet_banking.sql:/docker-entrypoint-initdb.d/internet_banking.sql
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  spring-boot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: spring-boot-backend
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/internet_banking
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - mysql
    command: [ "sh", "-c", "sleep 10 && java -jar backend.jar" ]
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
